// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6k5sCXTfCdQYbHIsCSDN0tcV4XhhogYo',
    appId: '1:557554364705:web:167abfa4cf4b70ab33ce60',
    messagingSenderId: '557554364705',
    projectId: 'eggguardian-19ee3',
    authDomain: 'eggguardian-19ee3.firebaseapp.com',
    storageBucket: 'eggguardian-19ee3.firebasestorage.app',
    measurementId: 'G-P79YMWEPCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDok0-Rf0pMxtV6gteBBVad6bfpTa3Bjts',
    appId: '1:557554364705:android:aa6445ed3d2ef5b633ce60',
    messagingSenderId: '557554364705',
    projectId: 'eggguardian-19ee3',
    storageBucket: 'eggguardian-19ee3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzQGz3Zwrwj_19F37ZBH-R4YUSpojJtAU',
    appId: '1:557554364705:ios:eca2d94647e5acc133ce60',
    messagingSenderId: '557554364705',
    projectId: 'eggguardian-19ee3',
    storageBucket: 'eggguardian-19ee3.firebasestorage.app',
    iosBundleId: 'com.example.eggguardianFinalv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzQGz3Zwrwj_19F37ZBH-R4YUSpojJtAU',
    appId: '1:557554364705:ios:eca2d94647e5acc133ce60',
    messagingSenderId: '557554364705',
    projectId: 'eggguardian-19ee3',
    storageBucket: 'eggguardian-19ee3.firebasestorage.app',
    iosBundleId: 'com.example.eggguardianFinalv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6k5sCXTfCdQYbHIsCSDN0tcV4XhhogYo',
    appId: '1:557554364705:web:0fd4fd33ff7f2efe33ce60',
    messagingSenderId: '557554364705',
    projectId: 'eggguardian-19ee3',
    authDomain: 'eggguardian-19ee3.firebaseapp.com',
    storageBucket: 'eggguardian-19ee3.firebasestorage.app',
    measurementId: 'G-3CNMPTRCE5',
  );

}